

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipl-assignment
  labels:
    app: ipl-assignment
spec:
  replicas: 2  # Adjusted from 2 to 1
  selector:
    matchLabels:
      app: ipl-assignment
  template:
    metadata:
      labels:
        app: ipl-assignment
    spec:
      containers:
        - name: ipl-assignment
          image: assignment:1.0
          ports:
            - containerPort: 5000
          env:
            - name: KAFKA_HOST
              value: "host.docker.internal:9094"
            - name: REDIS_HOST
              value: "host.docker.internal"
            - name: MYSQL_URL
              value: "jdbc:mysql://192.168.1.106:1000/ipl"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ipl-assignment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ipl-assignment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: ipl-assignment-service
spec:
  selector:
    app: ipl-assignment
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30006


